jobs:
  include:
    - name: Python with one level Output Directory and Input directory provided
      os: linux
      dist: focal
      arch: amd64
      language: python
      addons:
        sbom:
          on:
            branch: main
          run_phase: before_script
          input_dir: '/python'
          output_dir: '/python'
          output_format: spdx-json
        deploy:
          - provider: releases
            edge: true
            file_glob: true
            file: 
              - 'python/*.json'
              - 'python/*.txt'
            token: $GHTOKEN
            on:
              branch: AnkitM2212-patch-deploy_1
      script:
        - cd python
        - python hello_world.py
        - pip install -r requirements.txt
    - name: Python with two level Output Directory and Input directory provided
      os: linux
      dist: focal
      arch: amd64
      language: python
      addons:
        sbom:
          on:
            branch: main
          run_phase: before_script
          input_dir: '/python'
          output_dir: '/python/result_sbom'
          output_format: spdx-json
        deploy:
          - provider: releases
            edge: true
            file_glob: true
            file: 
              - 'result_sbom/python/*.json'
            token: $GHTOKEN
            on:
              branch: AnkitM2212-patch-deploy_1
      script:
        - cd python
        - python hello_world.py
        - pip install -r requirements.txt
